# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-23 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180823_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
